apiVersion: v1
kind: Service
metadata:
name: node-app-service
spec:
selector:
app: node-app
ports:
- protocol: TCP
port: 3000 # porta do serviço (cluster-internal)
targetPort: 3000 # porta no container
type: ClusterIP # service interno do cluster