# Dockerfile para imagem NGINX customizada
FROM nginx:stable-alpine


# Copia o arquivo de configuração personalizado para o container nginx
COPY default.conf /etc/nginx/conf.d/default.conf


# Expõe a porta 80 (http)
EXPOSE 80


# O comando padrão da imagem nginx já inicia o servidor